# Generated by Django 4.2.1 on 2023-06-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('one_h_percent', models.FloatField()),
                ('twentyFour_h_percent', models.FloatField()),
                ('seven_d_percent', models.FloatField()),
                ('market_cap', models.FloatField()),
                ('volume_24h', models.FloatField()),
                ('circulating_supply', models.FloatField()),
            ],
        ),
    ]
